# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TP' do
  pod 'AppCenter/Crashes', '~> 2.1.0'
  pod 'AppCenter/Analytics', '~> 2.1.0'
  pod 'AppCenterReactNativeShared', '~> 2.1.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TP

  

  platform :ios, '9.0'
  #pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  target 'TPTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TP-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TP-tvOS

  target 'TP-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
