# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TP' do
  pod 'Firebase/Messaging', '~> 6.3.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TP

  

  platform :ios, '9.0'
  #pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNSound', :path => '../node_modules/react-native-sound'


end
