# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TP' do
  pod ‘Firebase/Core’
  pod ‘Firebase/Messaging’

  # Comment the next line if you don't want to use dynamic frameworks
 # use_frameworks!

  # Pods for TP

  

  platform :ios, '9.0'
  #pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

 

end


